DROP TABLE IF EXISTS user;

CREATE TABLE user
(
	id BIGINT(20) UNSIGNED NOT NULL COMMENT '主键ID',
	name VARCHAR(30) NOT NULL COMMENT '姓名',
	username VARCHAR(100) NOT NULL COMMENT '用户名',
	password VARCHAR(32) NOT NULL DEFAULT '' COMMENT '密码',
	gender CHAR(6) NULL COMMENT '性别',
	age TINYINT(3) NULL COMMENT '年龄',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	favor VARCHAR(100) NULL COMMENT '兴趣爱好',
	app_no VARCHAR(20) NOT NULL COMMENT '租户编号',
	version INT(11) UNSIGNED NOT NULL DEFAULT 1 COMMENT '乐观锁版本号',
	deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标识符',
	PRIMARY KEY (id)
);